apiVersion: v1
kind: Service
metadata:
  name: deepseek-text
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: deepseek-text
  sessionAffinity: None
  type: ClusterIP