apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
status:
  replicas: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n
          ports:
            - containerPort: 5678
              protocol: TCP
          env:
            - name: N8N_BASIC_AUTH_ACTIVE
              value: 'true'
            - name: N8N_BASIC_AUTH_USER
              value: admin
            - name: N8N_BASIC_AUTH_PASSWORD
              value: admin
            - name: N8N_HOST
              value: localhost
            - name: N8N_PORT
              value: '5678'
            - name: N8N_PROTOCOL
              value: http
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
