apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-k8s-role
rules:
  - apiGroups: ['', 'apps', 'rbac.authorization.k8s.io']
    resources: ['deployments', 'services', 'pods', 'roles', 'rolebindings']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-k8s-role-binding
subjects:
  - kind: ServiceAccount
    name: demo-k8s
roleRef:
  kind: Role
  name: demo-k8s-role
  apiGroup: rbac.authorization.k8s.io
